# Default data extraction configuration (aligned with dataset pipeline).
pgn_paths: []
max_games: null
transforms: [identity, flip_horizontal]
target:
  type: selfplay
  stockfish_path: null
  depth: null
  nodes: null
  multipv: 8
  temperature: 1.0
shuffle: true
num_workers: 0
pin_memory: false
