# Hydra configuration for data extraction and teacher targets.
pgn_paths: []
max_games: null
output_dir: data/processed
augmentations:
  enable: true
  transforms: [identity, flip_horizontal]
target:
  type: selfplay  # or "stockfish"
  stockfish_path: null
  depth: 12
  nodes: null
  multipv: 8
  temperature: 1.0
