model:
  num_moves: 4672
  d_model: 512
  nhead: 8
  depth: 8
  dim_feedforward: 2048
  dropout: 0.1
  use_act: false

pgn_paths: []
stockfish_path: /path/to/stockfish

inference:
  max_loops: 1
  min_loops: 1
  use_act: false
  entropy_threshold: null
  act_threshold: 0.5

limit:
  depth: 12
  nodes: null
  movetime: null

multipv: 5
max_positions: 100
device: auto
checkpoint: null
