model:
  num_moves: 4672
  d_model: 512
  nhead: 8
  depth: 8
  dim_feedforward: 2048
  dropout: 0.1
  use_act: false

checkpoint: null
num_games: 2
max_moves: 60
opponent: random
device: auto
inference_max_loops: 2
