model:
  num_moves: 4672
  d_model: 256
  nhead: 8
  depth: 4
  dim_feedforward: 1024
  dropout: 0.1
  use_act: true

checkpoint: null
num_games: 10
max_moves: 200
output_pgn: data/selfplay/selfplay.pgn
output_dataset: data/selfplay/selfplay.pt
device: auto
inference_max_loops: 4
temperature: 1.0
mcts_num_simulations: 256
mcts_c_puct: 1.5
mcts_dirichlet_alpha: 0.3
mcts_dirichlet_epsilon: 0.25
mcts_eval_batch_size: 16
train_after: true
train_config: configs/train.yaml
eval_engine_path: "/opt/homebrew/bin/stockfish"
eval_depth: 12
eval_nodes: null
eval_movetime: null
eval_multipv: 2
eval_print_moves: false
eval_summary_thresholds:
  mistake: 50
  blunder: 150
max_datasets: 30
train_every_batches: 1
run_forever: true
max_batches: null
max_pgn_games: 1000
