model:
  num_moves: 4672
  d_model: 256
  nhead: 8
  depth: 4
  dim_feedforward: 1024
  dropout: 0.1
  use_act: true

checkpoint: null
num_games: 10
max_moves: 200
output_pgn: data/selfplay/selfplay.pgn
output_dataset: data/selfplay/selfplay.pt
device: auto
inference_max_loops: 1
temperature: 1.0
mcts_num_simulations: 16
mcts_c_puct: 1.5
mcts_dirichlet_alpha: 0.3
mcts_dirichlet_epsilon: 0.25
train_after: true
train_config: configs/train.yaml
eval_engine_path: "/opt/homebrew/bin/stockfish"
eval_depth: 12
eval_nodes: null
eval_movetime: null
eval_log_interval: 1
eval_multipv: 2
max_datasets: 1
train_every_batches: 1
run_forever: false
max_batches: null
