model:
  num_moves: 4672
  d_model: 512
  nhead: 8
  depth: 8
  dim_feedforward: 2048
  dropout: 0.1
  use_act: false

data:
  pgn_paths: []
  max_games: 1
  transforms: [identity, flip_horizontal]
  target:
    type: selfplay
    stockfish_path: "/opt/homebrew/bin/stockfish"
    depth: null
    nodes: null
    multipv: 8
    temperature: 1.0
  selfplay_datasets: []
  shuffle: true
  num_workers: 0
  pin_memory: false

optim:
  lr: 0.0003
  weight_decay: 0.01
  betas: [0.9, 0.999]
  grad_accum_steps: 1
  use_amp: false

training:
  epochs: 1
  batch_size: 32
  k_train: 4
  detach_prev_policy: true
  act_weight: 0.0
  value_loss: mse
  device: auto
  log_interval: 1

checkpoint:
  directory: checkpoints
  save_interval: 0

logging:
  enabled: true
  tracking_uri: null
  experiment: chessref
  run_name: null
